// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://qfjdfylkvpjwnugxtcwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmamRmeWxrdnBqd251Z3h0Y3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2ODAyNDYsImV4cCI6MjEwMzI1NjI0Nn0.ONrAbKK9D2pU1jxl2KMMWmcOAHp4Y66DunjSsxQE8ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});